## 1️⃣  tests/test_chat.py  – verifies the  /chat  route and intent handling                                                                                                                                                                              
                                                                                                                                                                                                                                                        
# backend/tests/test_chat.py                                                                                                                                                                                                                           
import json                                                                                                                                                                                                                                            
from fastapi.testclient import TestClient                                                                                                                                                                                                              
from main import app  # the FastAPI instance defined in backend/main.py                                                                                                                                                                                
                                                                                                                                                                                                                                                        
client = TestClient(app)                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                        
def test_chat_endpoint_returns_answer_and_recipes():                                                                                                                                                                                                   
    """When the intent is detected as 'search', the endpoint should return a list of recipes."""                                                                                                                                                       
    payload = {                                                                                                                                                                                                                                        
        "message": "show me recipes with chicken"                                                                                                                                                                                                      
    }                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                        
    response = client.post("/chat", json=payload)                                                                                                                                                                                                      
    assert response.status_code == 200                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                        
    data = response.json()                                                                                                                                                                                                                             
    # The endpoint always returns an 'answer' field and a 'recipes' list                                                                                                                                                                               
    assert "answer" in data                                                                                                                                                                                                                            
    assert isinstance(data["recipes"], list)                                                                                                                                                                                                           
                                                                                                                                                                                                                                                        
    # The test data in `recipes.json` contains many entries, so we expect at least 1 result                                                                                                                                                            
    # (the real service may filter; we only check that the response shape is correct)                                                                                                                                                                  
    assert len(data["recipes"]) >= 0  # zero is allowed for unmatched queries     