# backend/exceptions.py                                                                                                                                                                                                                                
from fastapi import HTTPException, status                                                                                                                                                                                                              
                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                            
# ----------------------------------------------------------------------                                                                                                                                                                               
# Base class for all domain‑specific errors                                                                                                                                                                                                            
# ----------------------------------------------------------------------                                                                                                                                                                               
class AppError(Exception):                                                                                                                                                                                                                             
    """Base class for custom domain errors."""                                                                                                                                                                                                         
    status_code: int = status.HTTP_500_INTERNAL_SERVER_ERROR                                                                                                                                                                                           
    detail: str = "Unexpected server error"                                                                                                                                                                                                            
                                                                                                                                                                                                                                                
    def to_http_exception(self) -> HTTPException:                                                                                                                                                                                                      
        """Convert the custom error into a FastAPI HTTPException."""                                                                                                                                                                                   
        return HTTPException(status_code=self.status_code, detail=self.detail)                                                                                                                                                                         
                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                
# ----------------------------------------------------------------------                                                                                                                                                                               
# Specific errors                                                                                                                                                                                                                                      
# ----------------------------------------------------------------------                                                                                                                                                                               
class RecipeNotFound(AppError):                                                                                                                                                                                                                        
    """Raised when a recipe ID cannot be found in the data store."""                                                                                                                                                                                   
    status_code = status.HTTP_404_NOT_FOUND                                                                                                                                                                                                            
    detail = "Recipe not found"                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                            
class PDFParseError(AppError):                                                                                                                                                                                                                         
    """Raised when the PDF parser cannot produce a valid Recipe."""                                                                                                                                                                                    
    status_code = status.HTTP_422_UNprocessable_ENTITY                                                                                                                                                                                                 
    detail = "Unable to parse the supplied PDF"                                                                                                                                                                                                        
                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                            
class AIServiceError(AppError):                                                                                                                                                                                                                        
    """Raised when an external AI service (e.g. Groq) fails or returns an error."""                                                                                                                                                                    
    status_code = status.HTTP_502_BAD_GATEWAY                                                                                                                                                                                                          
    detail = "AI service communication failure"       